export const ErrorCode = {
  // 400 Bad Request
  INVALID_REQUEST: 'INVALID_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  PAYMENT_ATTEMPT_INVALID: 'PAYMENT_ATTEMPT_INVALID',
  CANNOT_PERSIST_DERIVED_STATE: 'CANNOT_PERSIST_DERIVED_STATE',
  RETURN_URL_CANNOT_CONFIRM_PAYMENT: 'RETURN_URL_CANNOT_CONFIRM_PAYMENT',

  // 401 Unauthorized
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',

  // 403 Forbidden
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  OWNERSHIP_MISMATCH: 'OWNERSHIP_MISMATCH',
  UNAUTHORIZED_TRANSITION_ACTOR: 'UNAUTHORIZED_TRANSITION_ACTOR',

  // 404 Not Found
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  MEAL_OPTION_NOT_FOUND: 'MEAL_OPTION_NOT_FOUND',

  // 409 Conflict
  CONFLICT: 'CONFLICT',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  TABLE_CAPACITY_CHANGED: 'TABLE_CAPACITY_CHANGED',
  EVENT_CAPACITY_EXCEEDED: 'EVENT_CAPACITY_EXCEEDED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  TERMINAL_STATE_VIOLATION: 'TERMINAL_STATE_VIOLATION',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',
  CONTRACT_ALREADY_ACCEPTED: 'CONTRACT_ALREADY_ACCEPTED',

  // 422 Unprocessable Entity
  BUSINESS_INVARIANT_VIOLATION: 'BUSINESS_INVARIANT_VIOLATION',
  EVENT_NOT_OPERABLE: 'EVENT_NOT_OPERABLE',
  QUOTE_EXPIRED: 'QUOTE_EXPIRED',
  QUOTE_ALREADY_USED: 'QUOTE_ALREADY_USED',
  PAYMENT_SUBMISSION_ALREADY_REVIEWED: 'PAYMENT_SUBMISSION_ALREADY_REVIEWED',
  REFUND_NOT_ALLOWED: 'REFUND_NOT_ALLOWED',
  MEAL_OPTION_CLASSIFICATION_IMMUTABLE: 'MEAL_OPTION_CLASSIFICATION_IMMUTABLE',
  DEADLINE_EXCEEDED: 'DEADLINE_EXCEEDED',

  // 429 Rate Limited
  RATE_LIMITED: 'RATE_LIMITED',

  // 500 / 503 Server & Dependency
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
